### ISSUE TITLE
😀😍😖😄😞😠😕😖😓😅😧😠😑😢😭😮😖😶😢😶😕😯😨😞😷😅

### ISSUE THREAD

**Issue by Faerbit** [amoallim15/base-emoji#3]
😀😟😦😔😏😅😶😯😔😞😔😳😌😷😯😡😆😇😄😰😄😫😉😳😃😃😏😣😧😠😫😂😏😏😤😋😈😥😵😘😛😟😲😊😘😢😗😒😏😚😆😝😠😖😟😊😙😘😮😱😯😐😬😁😝😱😴😛😈😩😔😣😯😅😍😳😌😶😤😶😂😐😛😤😛😥😴😖😔😞😈😖😑😁😓😏😞😭😅😵😋😳😥😭😨😘😅😏😢😳😘😊😃😣😪😔😞😦😍😱😦😦😁😨😤😟😁😅😃😴😔😬😠😃😄😡😶😁😷😂😋😟

**Comment by amoallim15** [comment]
😀😄😝😡😓😢😟😘😜😶😇😰😯😔😂😄😙😡😈😞😂😯😁😠😦😩😏😨😷😁😭😏😉😏😕😷😒😍😓😞😰😑😑

**Comment by ukozi** [comment]
😀😊😋😘😍😜😇😢😰😰😍😜😗😅😮😟😣😇😡😆😣😐😟😞😕😝😩😪😖😝😰😐😎😍😲😭😌😂😣😃😢😖😦😘😚😅😁😉😎😜😊😪😫😴😂😋😡😦😛😦😋😗😁😔😩😰😄😷😭😇😍😤😬😃😍😩😮😉😝😑😭😥😦😭😬😱😩😰😄😱😃😬😛😠😳😂😅😗😠😰😫😎😝😏😫😉😕😌😯😭😱😮😁😞😦😶😍😯😱😫😜😁😊😰😠😇😗😳😜😏😳😔😪😃😟😃😜😙😗😪😨😜😦😦😙😖😓😙😢😕😝😔😚😴😫😝😲😟😜😱😁😮😶😚😮😆😮😴😋😮😷😉😴😪😠😞😋😩😑😯😣😧😓😯😖😜😗😍😠😤😄😒😘😵😱😣😵😆😓😑😛😎😊😏😪😳😭😲😎😩😭😖😎😱😜😂😕

**Comment by adamwojt** [comment]
``` 
'😀😶😇😭😳😋😧😳😦😰😒😋😗😯😅😧😉😮😏😔😝😧😓😉😂😤😧😒😅😠😤😪😶😳😰😛😖😟😵😴😕😎😩😦😮'

**Comment by amoallim15** [comment]
`😀😅😵😒😑😷😗😚😜😥😦😎😏😑😁😂😠😴😶😇😫😅😗😩😄😭😞😯😷😒😏😠😈😟😓😴😩😳😞😒😝😤😯😛😨😘😵😌😞😘😲😪😏😇😍😔😁😵😟😈😙😬😯😛😯😝😤😁😕😲😒😔😦😆😒😃😓😳😌😶😖😭😈😆😤😣😶😗😧😭😇😃😧😷`

**Comment by amoallim15** [comment]
`😀😗😕😘😬😄😛😑😪😶😌😤😩😝😭😘😅😓😂😴😡😷😡😢😧😦😩😭😃😷😰😬😴😢😮😜😢😰😛😧😁😏😨😍😚😏😍😪😲😩😰😟😊😩😪😧😕😄😭😱😭😃😬😍😢😄😟😕😉😴😎😕😰😲😆😠😲😑😎😛😋😝😗😖😋😧😘😜😥😰😑😏😅😩😖😯😄😪😩😓😮😷😛😵😌😜😄😅😅😜😪😗😣😵😜😨😥😖😈😄😪😦😣😩😰😎😆😚😔😜😳😘😧😠😰😷😷😋😔😅😡😈😳😪😪😋😥😊😯😨😗😎😷😃😙😡😄😍😶😧😅😖😥😭😱😶😔😲😬😯😇😨😌😶😔😅😇😞😚😡😷😲😯😫😖😗😑😔😅😂😣😆😖😓😍😮😢😳😓😅😏😃😣😪😗😋😧😰😂😕😡😡😨😥😍😞😐😑😜😑😩😌😮😴😊😘😡😯😇😛😛😟😡😢😣😨😦😑😈😒😅😞😝😤😬😥😉😩😯😅😫😣😬😚😷😡😝😛😆😑😩😆😳😦😭😌😌😊😝😩😁😃😍😡😄😉😒😧😖😮😆😯😕😢😓😭😂😥😢😵😙😖😃😋😳😖😞😱😬😈😞😁😘😩😲😍😶😯😁😜😁😆😴😋😠😓😖😍😟😣😃😄😅😌😯😧😫😵😦😍😮😬😧😱😆😮😇😲😯😍😣😜😢😄😂😠😯😘😨😦😗`
